import os
import subprocess
import sys
import sysconfig

from setuptools import find_packages
from setuptools import setup
from setuptools.command.install import install

# Version information
# We do like numpy: we have a major/minor/patch hand-written version written
# here. If we find the git commit (either via "git" command execution or in a
# dlg/version.py file) we append it to the VERSION later.
# The RELEASE flag allows us to create development versions properly supported
# by setuptools/pkg_resources or "final" versions.
MAJOR   = 0
MINOR   = 2
PATCH   = 1
RELEASE = True
VERSION = '%d.%d.%d' % (MAJOR, MINOR, PATCH)
VERSION_FILE = 'opencluster/version.py'

def get_git_version():
    out = subprocess.check_output(['git', 'rev-parse', 'HEAD'])
    return out.strip().decode('ascii')

def get_version_info():
    git_version = 'Unknown'
    if os.path.exists('.git'):
        git_version = get_git_version()
    full_version = VERSION
    if not RELEASE:
        full_version = '%s.dev0+%s' % (VERSION, git_version[:7])
    return full_version, git_version


def write_version_info():
    tpl = """
# THIS FILE IS GENERATED BY DALIUGE'S SETUP.PY
# DO NOT MODIFY BY HAND
version = '%(version)s'
git_version = '%(git_version)s'
full_version = '%(full_version)s'
is_release = %(is_release)s

if not is_release:
    version = full_version
"""
    full_version, git_version = get_version_info()
    with open(VERSION_FILE, 'w') as f:
        info = tpl % {'version': VERSION,
                      'full_version': full_version,
                      'git_version': git_version,
                      'is_release': RELEASE}
        f.write(info.strip())

# Every time we overwrite the version file
write_version_info()

install_requires = [
    "Pyro4",
    "psutil",
    "pyzmq",
    "web.py"
]

# Packages that need to be installed from somewhere different than PyPI
dependency_links = [
    # None at the moment
]

setup(
    name='opencluster',
    version=get_version_info()[0],
    packages=['opencluster', 'opencluster.ui'],
    package_dir={'opencluster': 'opencluster'},
    url='https://github.com/astroitlab/opencluster',
    license='LGPLv2+',
    author='Shoulin Wei',
    author_email='weishoulin@astrolab.cn',
    description='Distributed Computing API',
    install_requires=install_requires,
    dependency_links=dependency_links)
